const EMAIL_TEMPLATES={"A": "件名：【合同経営】労働条件通知書（パート・有期用）雛形のダウンロードのご案内\n\n{会社名}\n{ご担当者名} 様\n\n社会保険労務士法人 合同経営です。雛形のご請求をありがとうございます。\n2026年10月1日改正に対応した「労働条件通知書（パート・有期用）」の雛形・記載例・使い方ガイドは、次のリンクからダウンロードできます。\n\nダウンロード：【ダウンロード先URL】\n（有効期限：【　】日間。期限を過ぎた場合は、このメールに返信してください）\n\n■ 使い方\n・「使い方ガイド」の「２．記入欄の埋め方」の順に、雛形の空欄（【　】で示した箇所）を埋めてください。\n・今お使いの様式に1項目を足すだけで済ませたい場合は、ガイドの「７．追記文案」をご覧ください。\n・有期契約の更新は新たな雇入れに当たります。10月1日以降の契約更新から新様式で交付してください。\n\n■ ご利用条件\n雛形は貴社の自社利用に限ります。再配布・転売はできません。詳しくは雛形巻末の「ご利用条件」をご覧ください。\n\n■ 様式の点検・改訂のご支援\n今お使いの様式の点検（個別チェック。16,500円／1様式、税込。税抜 15,000円）や、給与ソフト出力・Excel様式の改訂をご希望の場合は、このメールに氏名等を記入していない空欄の様式を添付して返信してください。資料を拝見したうえで、納期をご相談します（当法人の顧問先の皆様には、顧問契約に基づき別途ご案内します）。\n\n――――――――――――――――――――\n社会保険労務士法人 合同経営　受付担当：林\n住所：〒760-0080　香川県高松市木太町3396番地11\n電話：087-812-5031　FAX：087-812-5036\nメール：sr@godo-k.co.jp\nこのメールは、フォームからご請求いただいた方に自動送信しています。\n顧問先の皆様には、顧問契約に基づき、法改正に関するご案内をお送りしています。一般のお客様には、フォームで「受け取る」を選ばれた方にのみお送りします。いずれも不要になった場合は sr@godo-k.co.jp までお知らせください。次回から送信しません。\n――――――――――――――――――――", "B": "件名：【合同経営】お申込みを受け付けました（{お申込みの内容}）\n\n{会社名}\n{ご担当者名} 様\n\n社会保険労務士法人 合同経営です。お申込みをありがとうございます。次の内容で受け付けました。\n\nお申込みの内容：{お申込みの内容}\n受付日時：{送信日時}\n\n■ 今後の流れ\n・雛形一式：お申込み確認後3営業日以内に、ダウンロード先をメールでお送りします。\n・個別チェック・適用支援・社員研修会：資料を拝見したうえで、納期をご相談します。担当（林）から2営業日以内にご連絡し、資料の受領後2営業日以内に納期と金額をお知らせします。点検をご希望の様式や規程は、氏名等を記入していない空欄のものを、このメールに添付して返信してください。社員研修会はご希望の日時と人数をお知らせください。\n\n■ 料金とお支払い\n料金は顧問契約に基づき、担当からご案内します。ご請求が生じる場合は顧問料と合わせてご請求します。\n\n――――――――――――――――――――\n社会保険労務士法人 合同経営　受付担当：林\n住所：〒760-0080　香川県高松市木太町3396番地11\n電話：087-812-5031　FAX：087-812-5036\nメール：sr@godo-k.co.jp\nこのメールは、フォームからお申込みいただいた方に自動送信しています。\n顧問契約に基づき、法改正に関するご案内をお送りしています。不要になった場合は sr@godo-k.co.jp までお知らせください。次回から送信しません。\n――――――――――――――――――――", "C": "件名：【合同経営】お申込みを受け付けました（{お申込みの内容}）\n\n{会社名}\n{ご担当者名} 様\n\n社会保険労務士法人 合同経営です。お申込みをありがとうございます。次の内容で受け付けました。\n\nお申込みの内容：{お申込みの内容}\n受付日時：{送信日時}\n\n■ 今後の流れ\n・雛形一式：内容を確認のうえ請求書をメールでお送りします。ご入金確認後3営業日以内に、ダウンロード先をメールでお送りします。\n・個別チェック・適用支援・社員研修会：資料を拝見したうえで、納期をご相談します。担当（林）から2営業日以内にご連絡し、資料の受領後2営業日以内に納期と金額をお知らせします。点検をご希望の様式や規程は、氏名等を記入していない空欄のものを、このメールに添付して返信してください。社員研修会はご希望の日時と人数をお知らせください。納期と金額にご了承いただいた後、請求書をお送りし、ご入金確認後に作業を始めます。\n\n■ お支払い\n請求書を発行しますので、銀行振込でお支払いください（振込手数料はお客様のご負担です）。料金は料金表（【料金表URL】）のとおりです。\n\n――――――――――――――――――――\n社会保険労務士法人 合同経営　受付担当：林\n住所：〒760-0080　香川県高松市木太町3396番地11\n電話：087-812-5031　FAX：087-812-5036\nメール：sr@godo-k.co.jp\nこのメールは、フォームからお申込みいただいた方に自動送信しています。\n法改正に関する案内メールは、フォームで「受け取る」を選ばれた方にのみお送りします。不要になった場合は sr@godo-k.co.jp までお知らせください。次回から送信しません。\n――――――――――――――――――――"};
'use strict';
const form=document.querySelector('#application');
if(form){
 const product=()=>form.querySelector('[name=product]:checked')?.value||'';
 const contract=()=>form.querySelector('[name=contract]:checked')?.value||'';
 const hint=document.querySelector('#route-hint');
 const update=()=>{const p=product(),c=contract();const addr=form.elements.address;document.querySelector('#address-row').hidden=false;addr.required=c==='no';addr.disabled=false;document.querySelector('#address-row small').textContent=c==='no'?'必須':'任意';document.querySelector('#format-row').hidden=!p.startsWith('n-');form.querySelectorAll('[name=format]').forEach(el=>el.disabled=!p.startsWith('n-'));hint.textContent=p==='n-template'?'労働条件通知書の雛形は無償です。自動返信メールでダウンロード先をご案内します。':c==='yes'?'顧問契約に基づき別途ご案内します。個別チェック＋適用支援（カスハラ対策）、個別チェック・適用支援（労働条件通知書）、社員研修会の納期は要相談です。':p==='h-template'?'一般価格 22,000円（税込）。請求書をご案内し、ご入金確認後3営業日以内にダウンロード先をお送りします。':'個別支援の納期は要相談です。内容と資料を確認したうえで、お見積り・納期をご案内します。';};
 const requested=new URLSearchParams(location.search).get('product');const initial=['h-check','h-support'].includes(requested)?'h-check-support':requested;form.querySelectorAll('[name=product]').forEach(el=>el.checked=el.value===initial);form.addEventListener('change',update);update();
 form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const d=new FormData(form),p=product(),c=contract(),route=p==='n-template'?'A':c==='yes'?'B':'C';const result=document.querySelector('#result');result.replaceChildren();const h=document.createElement('h2');h.textContent='入力内容・自動返信の確認';result.append(h);const notice=document.createElement('p');notice.className='notice';notice.textContent='確認用の表示です。お申込みは送信されていません。';result.append(notice);const dl=document.createElement('dl');dl.className='result-grid';const labels={company:'会社名',person:'ご担当者名',department:'部署・役職',email:'メール',phone:'電話番号',address:'所在地（番地まで）',staff:'従業員数',industry:'業種',message:'ご相談内容'};const row=(a,b)=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b||'未入力';dl.append(dt,dd);};row('ご希望の内容',form.querySelector('[name=product]:checked').parentElement.textContent.trim());row('顧問契約',c==='yes'?'あり':'なし');Object.entries(labels).forEach(([k,l])=>{row(l,d.get(k));});if(p.startsWith('n-'))row('現在の様式',d.getAll('format').join('・'));row('案内メール',d.has('mail')?'受け取る':'受け取らない');row('ご利用条件','同意');row('個人情報の取扱い','同意');result.append(dl);const title=document.createElement('h3');title.textContent='自動返信 '+route+' の案内イメージ';result.append(title);const reply=document.createElement('div');reply.className='reply';reply.textContent=EMAIL_TEMPLATES[route].replaceAll('{会社名}',d.get('company')).replaceAll('{ご担当者名}',d.get('person')).replaceAll('{お申込みの内容}',form.querySelector('[name=product]:checked').parentElement.textContent.trim()).replaceAll('{送信日時}','制作確認用・実際の受付なし').replaceAll('【ダウンロード先URL】','［本番公開前に設定］').replaceAll('【　】日間','［本番公開前に設定］').replaceAll('【料金表URL】',p.startsWith('h-')?'harassment.html#detail':'notice.html#detail');result.append(reply);const back=document.createElement('button');back.className='button secondary';back.textContent='入力内容を修正する';back.type='button';back.addEventListener('click',()=>{result.hidden=true;form.hidden=false;form.scrollIntoView({behavior:'smooth'});});result.append(back);form.hidden=true;result.hidden=false;result.focus();result.scrollIntoView({behavior:'smooth'});});
}
